return {
	"nvim-lua/plenary.nvim",
	"editorconfig/editorconfig-vim",
	"tpope/vim-commentary",
	"tpope/vim-dispatch",
	"tpope/vim-fugitive",
	"nvim-telescope/telescope.nvim",
	"roobert/tailwindcss-colorizer-cmp.nvim",
	-- "ElmCast/elm-vim",
	-- "Quramy/vim-js-pretty-template",
	-- "SirVer/ultisnips",
	-- "Valloric/MatchTagAlways",
	-- "antoinemadec/FixCursorHold.nvim",
	-- "aserebryakov/vim-todo-lists",
	-- "ayu-theme/ayu-vim",
	-- "chrisbra/Colorizer",
	-- "epilande/vim-es2015-snippets",
	-- "epilande/vim-react-snippets",
	-- "ervandew/supertab",
	-- "flazz/vim-colorschemes",
	-- "folke/todo-comments.nvim",
	-- "gisphm/vim-gitignore",
	-- "hrsh7th/cmp-buffer",
	-- "hrsh7th/cmp-cmdline",
	-- "hrsh7th/cmp-nvim-lsp",
	-- "hrsh7th/cmp-path",
	-- "hrsh7th/nvim-cmp",
	-- "iamcco/markdown-preview.nvim",
	-- "ianks/vim-tsx",
	-- "jelera/vim-javascript-syntax",
	-- "junegunn/fzf",
	-- "mattn/emmet-vim",
	-- "moll/vim-node",
	-- "mxw/vim-jsx",
	-- "neovim/nvim-lspconfig",
	-- "nvim-neotest/neotest",
	-- "nvim-neotest/neotest-vim-test",
	-- "nvim-treesitter/nvim-treesitter", {"do": ":TSUpdate"},
	-- "quangnguyen30192/cmp-nvim-ultisnips",
	-- "quramy/tsuquyomi",
	-- "rking/ag.vim",
	-- "ruanyl/coverage.vim",
	-- "samodostal/image.nvim",
	-- "sergioramos/jsctags",
	-- "sheerun/vim-polyglot",
	-- "terryma/vim-expand-region",
	-- "terryma/vim-multiple-cursors",
	-- "vim-airline/vim-airline",
	-- "vim-airline/vim-airline-themes",
	-- "vim-test/vim-test",
	-- "wakatime/vim-wakatime",
	-- "whatyouhide/vim-gotham",
	-- "williamboman/nvim-lsp-installer",
	-- "xolox/vim-colorscheme-switcher",
	-- "xolox/vim-misc",
	-- "xolox/vim-session",
}
